// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA95C2OApvIARoX8MlFVaraq-UXcwOKgBA',
    appId: '1:24475077490:web:fbb0dc7fa3030acfefebeb',
    messagingSenderId: '24475077490',
    projectId: 'findom-6eb94',
    authDomain: 'findom-6eb94.firebaseapp.com',
    storageBucket: 'findom-6eb94.appspot.com',
    measurementId: 'G-5Z2RTW33LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOIFnjZDZGJ5n1y7TugVRfWpxY1rg1uM',
    appId: '1:24475077490:android:9648352369912c44efebeb',
    messagingSenderId: '24475077490',
    projectId: 'findom-6eb94',
    storageBucket: 'findom-6eb94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGVypJbz2AcWt2LTuJWFYb3ivEATxmZXQ',
    appId: '1:24475077490:ios:db8c3e2ca3c34178efebeb',
    messagingSenderId: '24475077490',
    projectId: 'findom-6eb94',
    storageBucket: 'findom-6eb94.appspot.com',
    iosBundleId: 'com.example.findhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGVypJbz2AcWt2LTuJWFYb3ivEATxmZXQ',
    appId: '1:24475077490:ios:db8c3e2ca3c34178efebeb',
    messagingSenderId: '24475077490',
    projectId: 'findom-6eb94',
    storageBucket: 'findom-6eb94.appspot.com',
    iosBundleId: 'com.example.findhome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA95C2OApvIARoX8MlFVaraq-UXcwOKgBA',
    appId: '1:24475077490:web:14a96a2ecf96b7d7efebeb',
    messagingSenderId: '24475077490',
    projectId: 'findom-6eb94',
    authDomain: 'findom-6eb94.firebaseapp.com',
    storageBucket: 'findom-6eb94.appspot.com',
    measurementId: 'G-0C5HVMHR2G',
  );
}
